# Basic Usage
The novelty sampler selects $n$ novel experimental conditions from a pool of candidate experimental conditions $X'$. The choice is informed based on the similarity of the candidate conditons $X'$ with respect to previously examined experiment conditons $X$.
We begin with importing the relevant packages.

In [1]:
from autora.experimentalist.sampler.novelty import novelty_sampler, novelty_score_sampler
import numpy as np

Next, we define the existing experimental conditons $X$.

In [2]:
X = np.array([1, 2, 3])

We define the candidate experimental conditons $X'$ from which we seek to sample.

In [3]:
X_prime = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Next, we need to specify how many samples we would like to collect. In this case, we pick $n=2$.

In [4]:
n = 2

Finally, we can call the novelty sampler. Note that $X'$ is the first argument to the sampler, followed by the "reference" conditions $X$, and the number of samples.

In [5]:
X_sampled = novelty_sampler(condition_pool = X_prime, reference_conditions = X, num_samples = n, metric = "euclidean", integration = "sum")
print(X_sampled)

[[10]
 [ 9]]


The novelty sampler also works for experiments with multiple indendent variables. In the following example, we define $X$ as a single experimental condition composed of three independent factors. We choose from a pool $X'$ composed of four experimental conditons.

In [6]:
X = np.array([[1, 1, 1]])
X_prime = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

Next, we sample a single experimental condition from the pool $X'$ which yields the greatest summed Euclidean distance to the existing condition in $X$.

In [7]:
X_sampled = novelty_sampler(condition_pool = X_prime, reference_conditions = X, num_samples = 1, metric = "euclidean", integration = "sum")
print(X_sampled)

[[10 11 12]]


We can also obtain "novelty" scores for the sampled experiment conditions using ``novelty_score_sampler''. The scores are z-scored with respect to all conditions from the pool. In the following example, we sample 2 conditions and return their novelty scores.

In [11]:
X_sampled, scores = novelty_score_sampler(condition_pool = X_prime, reference_conditions = X, num_samples = 2, metric = "euclidean", integration = "sum")
print(X_sampled)
print(scores)

[[10 11 12]
 [ 7  8  9]]
[1.35401943 0.43928867]


The novelty scores align with the sampled experiment conditions (in descending order of the novelty score).